#####  Welcome to Numpy
Numpy(Numerical Python) is an open source libary that's used in almost every field of science and engineering. it's universal standard for working with numerical data in python, and it's at the core of the scientific Python and pyData ecosystems. NumPy users include everone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, Scipy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

the NumPy library contains multidimensional array and matrix data structures (you'll find more information about this in later sections). It provides ndarray, a homegeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. it adds powerfull data strictures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous libraryof high-level mathematical functions that operate on these arrays and matrices.



#### How to import Numpy
To access numpy and its finctions import it in your python code like this:

import numpy as np

we shorten the imported name to np for better readability of code using numpy. This is a widely adopted convention that should follow so that anyone working with your code can easily understand it.

#### Reading the example code

if you aren't already comfortable with reading tutorials that contain a lot of code you might not know how to interpret a code block that looks like this:

>>> a = np.arange(6)
>>> a2 = a[np.newaxis, :]
>>> a2.shape
(1,6)

if you aren't familiar with this style, it's very easy to understand. if you see >>>, you're looking at input, or the code that you would enter. Everything that doesn't have >>> in front of it is output, or the results of running your code. this is the style you see when you run python on the command line, but if you're using Ipython you might see a different etyle. Note that it is not part of the code and will cause an error it typed or pasted into the Python shell. it can be safely typed or pasted into the Ipython shell.it can be safely typed or pasted into the Ipython shell; the >>> is ignored

##### What's the difference between a Python list and a Numpy array?

NumPy gives you an enourmous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a simple list, all of the elements in numPy array should be homogeneous. The matematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren't homogeneous.

why use NumPy?
NumPy arrays are faster and more compact than python lists. An array consumes less memory and  is convenient to use . NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

###### what is an array?
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. it has a grid of elements that can be indexed in various ways. The elements are all of the same Type, referred to as the array dtype.

an array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. the rank of the array is a tuple of integers giving the size of the array along each dimension.

one way we can initialize NumPy arrays is from Python lists, using nested lists for two- or  higher-dimensional data.

for example:
>>> a = np.array([1,2,3,4,5,6])
or
>>> a= np.array([1,2,3,4],[5,6,7,8],[9,10,11,12])

we can access the elements in the array using square brackets. When you're acessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you'll be acessing element "0".

>>> print(a[0])
[1,2,3,4]

#### More information about arrays

You might ocassionally hear an array referred to as a "ndarray" which is shorthand for "N-dimensional array." An N-dimensional array is a simply and array with any number of dimensions. You might also hear !-D, or one-dimensional array, 2-D, or two-dimensional array, ad so on. The NumPy ndarray class is ussed to represent both matrices and vectors. A vector is an array with a simple dimension (There's no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-d or higher dimensional arrays, the term tensor is also commonly used.

What are the attributes of an array?

An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape. the shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

in NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this

[[0.0.0.],
 [1.,1.,1.]]

 your array has 2 aces. the first axis has a lenght of 2 and the second axis has a length of 3.

 Just like in other Python container objects, the contents of an array can be accessed and modified by indexing or slicing the arrays. Unlike the typical container objects, differents arrays can share the same data, so changes made on one array might be visible in another.

Array attributes reflect information intrinsic to the array itself. If you need to get, or even set, properties of an array without creating a new array you can often access an array through its attributes.


#### how to create a basic array

To create a NumPy array, you can use the function np.array().

>>> import numpy as np
>>> a = np.array([1,2,3])

you can isualize your array this way:
Numpy Array
1
2
3

Be aware that these visualization are meant to simplify ideas and give you a basic understanding of NumPy concepts and mechanics. Arrays and array operations are much more complicated than are captured here!

Besides creating an array from a sequence of elements, you can easily create an array filled with 0's

>>> np.zeros(2)
array([0.,0.])

Or an array filled with 1's:

>>> np.ones(2)
array([1.,1.])

Or even an enpty array" the functions empty creates an array whose initial content is random and depends on the state of the memmory. the reason to use empty over zeros ( or something similar) is speed- just make sure to fill every element afterwards!

>>> # create an empty array with 2 elements
>>> np.empty(2)
array([3.14,42.]) # may vary

you can create an array with a range of elements:

>> np.arange(4)
array([0,1,2,3])

And even an array that contains a range of evenly space intervals, to do this, you will specify the first number, the last number and the step size.

>>> np.arange(2,9,2)
array([2,4,6,8])


you can also use np.linspace() to create an array with values that are spaced linearly in a specific interval:
np.linespace(0,10, nums = 5)
array([0., 2.5, 5., 7.5, 10.])

Specifying your date type

while the defeault data type is floating point (np.float64), you can explicity specify which data type you want using the dtyupe keyword.

>>> x = np.ones(2, dtype=np.int64)
>>> x
array([1,1])

##### Adding, removing, and sorting elements

sorting an element is simple with np.sort(). you can specify the axis,kind , and order when you call the function.
if you start with this sarray:

>>> arr = np.array([2,1,5,3,7,5,6,8])

you can quickly sort the numbers in ascending order with:

>>>np.sort(arr)
array([1,2,3,4,5,6,7,8])

in addition to sort, which returns a sorted copy of an array, you can use:
. argsort, which is an indirect sort along a specified axis,
. lexsort, which is an indirect stable sort on multiple keys,
. searchsorted, which will find elements in a sorted array, and
. partition, which is a partial sort.

if you start with these arrays?

>>> a = np.arrap([1,2,3,4])
>>> b = np.arrap([5,6,7,8])

You can concatenate them with np.concatenate().

>>> np.concatenate((a,b))
array([1,2,3,4,5,6,7,8])

Or, if you start with these arrays?

>>> x = np.array([[1,2],[3,4]])
>>> y = np.array([[5,6]])

you can concatenate them with:

>>> np.concatenate((x,y), axis=0)

array([[1,2],
       [3,4],
       [5,6]])

in order to remove elements from an array. it's simple to use indexing to select the elements that you want to keep.



### how do you know the shape and size ofan array?

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total of elements of the array, this is the product of the elements of the array's shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension. if, for example, you have a 2-d array with 2 rows and 3 columns, the shape of you array is (2,3).

for example if you create this array:

>>> x = np.array([[[1,2,3][,4,5,6]],[[1,2,3][4,5,6]]])

to find the number of dimensions of the array, run:

>>> x.ndin
3

to find the total number of elements in the array, run:

>>> x.size
12

and to find the shape of your array, run:

>>> x.shape
(2,2,3)

### Can you reshape a array?

Yes!
Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array  that you want to produce needs to have the same numbers of elements as the original array, if you starwith an array with 12 elements, you'll need to make sure that your new array also has a total of 12 elements.

if you start with this array:

>>> a = np.arange(6)
>>> print(a)
[0 1 2 3 4 5 6]

 you can use reshape() to reshape you array. For example, you canreshape this array to anarray with three rows and two columns:

 >>> b = a.reshape(3,2)
 >>> print(b)
 [[0 1]
  [2 3]
  [4 5]]

with np.reshape, you can specify a few of optional parameters:

>>> numpy.reshape(a, newshape=(1,6), order='C')
array([[0,1,2,3,4,5]])

a is the array to be reshaped.

newshape is the nre shape  you want. you can specify an integer or a tuple of integers. if you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

order: (order ='C') means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, (order= 'A') means  to read/write the elements on fortran-like index order if a is Fortran contiguos in memory, C-like order otherwise.(This is an optional parameter and doesn't need to be specified.)
 

#### How to convert a 1D array into a 2D array (how to add a new axis to an array)

You can use np.newaxis and np.expand_dims to increase the dimensions of you existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. this means that a 1D array will become a 2D array, a 2Darray will become  a 3D array, and so on.

for example, if you start with this array:

>>> a = np.array([1,2,3,4,5,6])
>>> a.shape
(6,)

you can use np.newaxis to add a new axis:

>>> a2 = a[np.newaxis, :]
>>> a2.shape
(1,6)

Or, for a column vector, you can insert an axis along the second dimension:

>>> col_vector = a[:, np.newaxis]
>>> col_vector.shape
(6,1)

you can also expand an array by inserting a new axis at a specified position with np.expand_dims.

for example, if you start with this array:

>>> a = np.array([1,2,3,4,5,6])
>>> a.shape
(6,)

You can use np.expand_dims to add an axis at index position 1 with:

>>> b = np.expand_dims(a, axis=1)
>>> b.shape
(6,1)

You can add an axis at index position 0 with:

>>> c = np.expand_dims(a, axis = 0)
>>> c.shape
(1,6)


#### indexing and slicing

you can index and slice NumPy arrays in the same ways you can slice Python Lists.

>>> data = np.array([1,2,3])
>>> data[1]
2
>>> data[0:2]
array([1,2])
>>> data[1:]
array([2,3])
>>> data [-2:]
array([2,3])

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. to do that, you'll need to subset, slice, and/or index your arrays

if you want to select values from your array that fulfll cretain conditions. it's straighforward with NumPy
 
 For example, if you start with this array:

 >>> a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

You can easily print all of the value in the array that are less than 5

>>> print(a[ a < 5 ])
[1 2 3 4]

You can also select, for example, numbers that are equal to or greater than 5, and use that conditional to index an array.

>>> five_up = (a >= 5)
>>> print(a[five_up])
[ 5 6 7 8 9 10 11 12]

you can select elements thar are divisible by 2;

>>> divisible_by_2 = a[a%2==0]
print(divisible_by_2)
[2 4 6 8 10 12]

Or you can select elements that satisy two conditions using the & and | operators:

>>> c = a[(a > 2) && (a < 11)]
>>> print(c)
[ 3 4 5 6 7 8 9 10 ]

you can also make use of the logical operators & and | in order to return boolean values that specify whether or not the values in an array fulfill a Certan condition. 

>>> five_up = ( a > 5 )| (a == 5)
>>> print(five_up)
  [[false false false false]
   [True True True True]
   [True True True True]]

you can use np.nonzero() to print the indices of elements that are, for example, less than 5:

 >>> b = np.nonzero(a < 5)
 >>> print(b)
 (array([0,0,0,0]), array([0,1,2,3]))

 in this example, a tuple was returned: one for each dimension. the first array represents the row indices where these values are found, and the second array represents the column indices where the values are found.

 if you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate onver the list of coordinate, and print them. for example;

 >>> list_of_coordinates = list(zip(b[0],b[1]))
 >>> for coord in list_of_coordinates:
        print(coord)
    (0,0)
    (0,1)
    (0,2)
    (0,3)
you can also use np.nonzero() to print the elements in an array that are less than 5 with:

>>> print(a[b])
[1 2 3 4]

>>> if the element you're looking for doesn't exist in the array, then the returned array of indices will be  empty. for example:

>>> not_there = np.nonzero(a == 42)
>>> print(not_there)
(array([],dtype=int64), array([],dtype=int64))