#####  Welcome to Numpy
Numpy(Numerical Python) is an open source libary that's used in almost every field of science and engineering. it's universal standard for working with numerical data in python, and it's at the core of the scientific Python and pyData ecosystems. NumPy users include everone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, Scipy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

the NumPy library contains multidimensional array and matrix data structures (you'll find more information about this in later sections). It provides ndarray, a homegeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. it adds powerfull data strictures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous libraryof high-level mathematical functions that operate on these arrays and matrices.



#### How to import Numpy
To access numpy and its finctions import it in your python code like this:

import numpy as np

we shorten the imported name to np for better readability of code using numpy. This is a widely adopted convention that should follow so that anyone working with your code can easily understand it.

#### Reading the example code

if you aren't already comfortable with reading tutorials that contain a lot of code you might not know how to interpret a code block that looks like this:

>>> a = np.arange(6)
>>> a2 = a[np.newaxis, :]
>>> a2.shape
(1,6)

if you aren't familiar with this style, it's very easy to understand. if you see >>>, you're looking at input, or the code that you would enter. Everything that doesn't have >>> in front of it is output, or the results of running your code. this is the style you see when you run python on the command line, but if you're using Ipython you might see a different etyle. Note that it is not part of the code and will cause an error it typed or pasted into the Python shell. it can be safely typed or pasted into the Ipython shell.it can be safely typed or pasted into the Ipython shell; the >>> is ignored

##### What's the difference between a Python list and a Numpy array?

NumPy gives you an enourmous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a simple list, all of the elements in numPy array should be homogeneous. The matematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren't homogeneous.

why use NumPy?
NumPy arrays are faster and more compact than python lists. An array consumes less memory and  is convenient to use . NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

###### what is an array?
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. it has a grid of elements that can be indexed in various ways. The elements are all of the same Type, referred to as the array dtype.

an array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. the rank of the array is a tuple of integers giving the size of the array along each dimension.

one way we can initialize NumPy arrays is from Python lists, using nested lists for two- or  higher-dimensional data.

for example:
>>> a = np.array([1,2,3,4,5,6])
or
>>> a= np.array([1,2,3,4],[5,6,7,8],[9,10,11,12])

we can access the elements in the array using square brackets. When you're acessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you'll be acessing element "0".

>>> print(a[0])
[1,2,3,4]

#### More information about arrays

You might ocassionally hear an array referred to as a "ndarray" which is shorthand for "N-dimensional array." An N-dimensional array is a simply and array with any number of dimensions. You might also hear !-D, or one-dimensional array, 2-D, or two-dimensional array, ad so on. The NumPy ndarray class is ussed to represent both matrices and vectors. A vector is an array with a simple dimension (There's no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-d or higher dimensional arrays, the term tensor is also commonly used.

What are the attributes of an array?

An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape. the shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

in NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this

[[0.0.0.],
 [1.,1.,1.]]

 your array has 2 aces. the first axis has a lenght of 2 and the second axis has a length of 3.

 Just like in other Python container objects, the contents of an array can be accessed and modified by indexing or slicing the arrays. Unlike the typical container objects, differents arrays can share the same data, so changes made on one array might be visible in another.

Array attributes reflect information intrinsic to the array itself. If you need to get, or even set, properties of an array without creating a new array you can often access an array through its attributes.


#### how to create a basic array

To create a NumPy array, you can use the function np.array().

>>> import numpy as np
>>> a = np.array([1,2,3])

you can isualize your array this way:
Numpy Array
1
2
3

Be aware that these visualization are meant to simplify ideas and give you a basic understanding of NumPy concepts and mechanics. Arrays and array operations are much more complicated than are captured here!

Besides creating an array from a sequence of elements, you can easily create an array filled with 0's

>>> np.zeros(2)
array([0.,0.])

Or an array filled with 1's:

>>> np.ones(2)
array([1.,1.])

Or even an enpty array" the functions empty creates an array whose initial content is random and depends on the state of the memmory. the reason to use empty over zeros ( or something similar) is speed- just make sure to fill every element afterwards!

>>> # create an empty array with 2 elements
>>> np.empty(2)
array([3.14,42.]) # may vary

you can create an array with a range of elements:

>> np.arange(4)
array([0,1,2,3])

And even an array that contains a range of evenly space intervals, to do this, you will specify the first number, the last number and the step size.

>>> np.arange(2,9,2)
array([2,4,6,8])


you can also use np.linspace() to create an array with values that are spaced linearly in a specific interval:
np.linespace(0,10, nums = 5)
array([0., 2.5, 5., 7.5, 10.])

Specifying your date type

while the defeault data type is floating point (np.float64), you can explicity specify which data type you want using the dtyupe keyword.

>>> x = np.ones(2, dtype=np.int64)
>>> x
array([1,1])

##### Adding, removing, and sorting elements

sorting an element is simple with np.sort(). you can specify the axis,kind , and order when you call the function.
if you start with this sarray:

>>> arr = np.array([2,1,5,3,7,5,6,8])

you can quickly sort the numbers in ascending order with:

>>>np.sort(arr)
array([1,2,3,4,5,6,7,8])

in addition to sort, which returns a sorted copy of an array, you can use:
. argsort, which is an indirect sort along a specified axis,
. lexsort, which is an indirect stable sort on multiple keys,
. searchsorted, which will find elements in a sorted array, and
. partition, which is a partial sort.

if you start with these arrays?

>>> a = np.arrap([1,2,3,4])
>>> b = np.arrap([5,6,7,8])

You can concatenate them with np.concatenate().

>>> np.concatenate((a,b))
array([1,2,3,4,5,6,7,8])

Or, if you start with these arrays?

>>> x = np.array([[1,2],[3,4]])
>>> y = np.array([[5,6]])

you can concatenate them with:

>>> np.concatenate((x,y), axis=0)

array([[1,2],
       [3,4],
       [5,6]])

in order to remove elements from an array. it's simple to use indexing to select the elements that you want to keep.



### how do you know the shape and size ofan array?

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total of elements of the array, this is the product of the elements of the array's shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension. if, for example, you have a 2-d array with 2 rows and 3 columns, the shape of you array is (2,3).

for example if you create this array:

>>> x = np.array([[[1,2,3][,4,5,6]],[[1,2,3][4,5,6]]])

to find the number of dimensions of the array, run:

>>> x.ndin
3

to find the total number of elements in the array, run:

>>> x.size
12

and to find the shape of your array, run:

>>> x.shape
(2,2,3)

### Can you reshape a array?

Yes!
Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array  that you want to produce needs to have the same numbers of elements as the original array, if you starwith an array with 12 elements, you'll need to make sure that your new array also has a total of 12 elements.

if you start with this array:

>>> a = np.arange(6)
>>> print(a)
[0 1 2 3 4 5 6]

 you can use reshape() to reshape you array. For example, you canreshape this array to anarray with three rows and two columns:

 >>> b = a.reshape(3,2)
 >>> print(b)
 [[0 1]
  [2 3]
  [4 5]]

with np.reshape, you can specify a few of optional parameters:

>>> numpy.reshape(a, newshape=(1,6), order='C')
array([[0,1,2,3,4,5]])

a is the array to be reshaped.

newshape is the nre shape  you want. you can specify an integer or a tuple of integers. if you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

order: (order ='C') means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, (order= 'A') means  to read/write the elements on fortran-like index order if a is Fortran contiguos in memory, C-like order otherwise.(This is an optional parameter and doesn't need to be specified.)
 

#### How to convert a 1D array into a 2D array (how to add a new axis to an array)

You can use np.newaxis and np.expand_dims to increase the dimensions of you existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. this means that a 1D array will become a 2D array, a 2Darray will become  a 3D array, and so on.

for example, if you start with this array:

>>> a = np.array([1,2,3,4,5,6])
>>> a.shape
(6,)

you can use np.newaxis to add a new axis:

>>> a2 = a[np.newaxis, :]
>>> a2.shape
(1,6)

Or, for a column vector, you can insert an axis along the second dimension:

>>> col_vector = a[:, np.newaxis]
>>> col_vector.shape
(6,1)

you can also expand an array by inserting a new axis at a specified position with np.expand_dims.

for example, if you start with this array:

>>> a = np.array([1,2,3,4,5,6])
>>> a.shape
(6,)

You can use np.expand_dims to add an axis at index position 1 with:

>>> b = np.expand_dims(a, axis=1)
>>> b.shape
(6,1)

You can add an axis at index position 0 with:

>>> c = np.expand_dims(a, axis = 0)
>>> c.shape
(1,6)


#### indexing and slicing

you can index and slice NumPy arrays in the same ways you can slice Python Lists.

>>> data = np.array([1,2,3])
>>> data[1]
2
>>> data[0:2]
array([1,2])
>>> data[1:]
array([2,3])
>>> data [-2:]
array([2,3])

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. to do that, you'll need to subset, slice, and/or index your arrays

if you want to select values from your array that fulfll cretain conditions. it's straighforward with NumPy
 
 For example, if you start with this array:

 >>> a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

You can easily print all of the value in the array that are less than 5

>>> print(a[ a < 5 ])
[1 2 3 4]

You can also select, for example, numbers that are equal to or greater than 5, and use that conditional to index an array.

>>> five_up = (a >= 5)
>>> print(a[five_up])
[ 5 6 7 8 9 10 11 12]

you can select elements thar are divisible by 2;

>>> divisible_by_2 = a[a%2==0]
print(divisible_by_2)
[2 4 6 8 10 12]

Or you can select elements that satisy two conditions using the & and | operators:

>>> c = a[(a > 2) && (a < 11)]
>>> print(c)
[ 3 4 5 6 7 8 9 10 ]

you can also make use of the logical operators & and | in order to return boolean values that specify whether or not the values in an array fulfill a Certan condition. 

>>> five_up = ( a > 5 )| (a == 5)
>>> print(five_up)
  [[false false false false]
   [True True True True]
   [True True True True]]

you can use np.nonzero() to print the indices of elements that are, for example, less than 5:

 >>> b = np.nonzero(a < 5)
 >>> print(b)
 (array([0,0,0,0]), array([0,1,2,3]))

 in this example, a tuple was returned: one for each dimension. the first array represents the row indices where these values are found, and the second array represents the column indices where the values are found.

 if you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate onver the list of coordinate, and print them. for example;

 >>> list_of_coordinates = list(zip(b[0],b[1]))
 >>> for coord in list_of_coordinates:
        print(coord)
    (0,0)
    (0,1)
    (0,2)
    (0,3)
you can also use np.nonzero() to print the elements in an array that are less than 5 with:

>>> print(a[b])
[1 2 3 4]

>>> if the element you're looking for doesn't exist in the array, then the returned array of indices will be  empty. for example:

>>> not_there = np.nonzero(a == 42)
>>> print(not_there)
(array([],dtype=int64), array([],dtype=int64))

#### how to create an array from existing data

you can easily use create a new array from a sextion of an existing array.

let's say you have this array:

>>> a = np array([1,2,3,4,5,6,7,8,9,10])

you can create a new array from a section of your array any time by specifying where you want to slice your array.

>>> arr1 = a[3:8]
>>> arr1
array([4,5,6,7,8])

here, you grabbed a section of your array from index position 3 through index position 8.

you can also stack two existing arrays, both vertically and horizontally

>>> a1 = np.array([[1,1],[2,2]])
>>> a1
array([1,1],
      [2,2])
>>> a2 = np.array([[3,3],[4,4]])

you can stack them vertically with vstack:

>>> np.vstack((a1,a1))
array([[1,1],
       [2,2],
       [3,3],
       [4,4]])

or stack them horizontally with hstack:

>>> np.hstack((a1,a2))
array([[1,1,3,3],[2,2,4,4]])

You can split an array into several smaller arrays using hsplit. you can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

let's say you have this array:
>>> np.arrange(1,25).reshape(2,12)
>>> x
array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

if you wanted to split this array into three equally shaped arrays, you would run:

>>> np.hsplit(x,3)
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]

if you wanted to split your array after the third and fourth column, you'd run:

>>> np.hsplit(x,(3,4))
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]

You can use the view method to create a new object that looks at the same data as the original array (a shallow copy).

views are an important NumPy concept! NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. this saves memory and is faster ( no copu of the data has to be made). however it's important to be aware of this - modifying data in a view also modifies the original array! 

let's say you create this array:

>>> a = np.arange(1,13).reshape(3,4)
>>> a
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

now we create an array b1 by slicing a and modify the first element of b1. This will modify the corresponding element in a as well!

>>> b1 = a[0, :]
>>> b1
array([1,2,3,4])
>>> b1[0] = 99
>>> b1
arrray([99,2,3,4])
>>> a
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

using the copy method will make a complete copy of the array and its data (a deep copy). to use on your array, you could run:

>>> b2 = a.copy()

### basic array operations

Once you've created your arrays, you can start to work with them let's say, for example, that you've created two arrays, one called "data" and one called "ones"

you can add the arrays together with the pluss sign.

>>> data = np.array([1,2])
>>> ones = np.ones(2, dtype=int)
>>> data + ones
array([2,3])

you can, of course, do more than just addition!

>>> data - ones
array([0, 1])
>>> data * data
array([1, 4])
>>> data/ones
array([1., 2.])

basic operations are simple with NumPy. if you want to find the sum of the elements in an array, you'd use sum(), this works for 1d arrays, 2d arrays and arrays in higher dimensions

>>>a = np.array([1, 2, 3, 4])
>>> a.sum()
10


to add the wors or the columns in a 2d array, you would specify the axis.

if you start with this array:

>>> b = np.array([[1, 1],[2, 2]])

you can sum onver the axis of rows with:

>>> b.sum(axis = 0)
array([3, 3])

you cansum over the axis of columns with:

>>> b.sum(axis=1)
array([2, 4])


### Broadcasting

There are times when you might want to carry out an operation between an array and a simgle number ( also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we'll call it "data") might contain information about distance in miles but you want to convert the information to kilemeters, you can perform this operation with:

>>> data = np.array([1.0, 2.0])
>>> data * 1.6
array([1.6, 3,2])

NumPy understands that the multiplication should happen with each cell. That concepts is called broadcasting. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1.  if the dimensions are not compatible, you will get a ValueError

### More usefull array operations

NumPy also performs aggregation functions. in addition to 'min','max' and 'sum', you can easily run 'mean' to get the average, 'prod' to get the result of multiplying the elements together, 'std' to get the standard deviation, and more.

>>> data.max()
2.0
>>> data.min()
1
>>> data.sum()
3

Let's start with this array, called "a"

>>>a = np.array([[0.45053314, 0.17296777, 0.34376245,0.5510652,
               [0.54627315, 0.05093587, 0.40067661, 0.55645993,
               [0.12697628, 0.82485143, 0.26590556, 0.5691710])

it's very common to want to aggregate along a row or column. By default, every NumPy aggregation function will return the aggregate of the entire array. To find the sum or the minimum of the elements in your array, run:

>>> a.sum()
4.8595784

or:

>>> a.min()
0.05093587

you can specify on which axis you want the aggregation function to be computed. For example, you can find the minimum value within each column by specifying

axis = 0.

>>> a.min(axis=0)
array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

the four values listed above correspond to the number of columns in your array. With a four-column array, you will get four values as your result.





### creating matrices

you can pass Python lists list of lists to create a 2-d array (or "matrix") to represent them in NumPy.
>>> data = np.array([[1, 2], [3, 4], [5, 6]])
>>> data
array([[1, 2],
       [3, 4],
       [5, 6]])

indexing and slicing operations are useful when you're manipulating matrices:

>>> data[0, 1]
2
>> data[1:3]
array([[3, 4],
       [5, 6]])
>>> data[0:2, 0]
array([1, 3])

You can aggregate matrices the same way you aggregate vectors:

>>> data.max()
6
>>> data.min()
1
>>> data.sum()
21

You can aggregate all the values in a matrix and you can aggregate them across columns or rows using the axis parameter:

>>> data.max(axis=0)
array([5, 6])
>>> data.max(axis=1)
array([2,4,5])

Once you've created your matrices, you cann add and multiply them using arithmetic operators if you have two matrices that are the same size.

>>> data = np.array([[1, 2], [3, 4]])
>>> ones = np.array([[1, 1], [1, 1]])
>>> data + ones
array([[2, 3],
       [4, 5]])

You can do these arithmetic operations on matrices of different sizes, but only if one matrix has only one column or one row. in this case, NumPy will use its broadcast rules for the operation.

>>> data = np.array([[1, 2], [3, 4], [5, 6]])
>>> ones_row = np.array([[1, 1]])
>>> data + ones_row
array([[2, 3],
       [4, 5],
       [6, 7]])

be aware that when NumPy prints N-dimensional arrays, the last axis is looped over the festest while the first axis is the slowest for instance

>>>np.ones((4, 3, 2))
array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

There are often instance where we want NumPy to initialize the values of an array. NumPy offers functions like ones() and zeros(), and the random.generator class for random number generation for that. All you need to do is pass the number of elements you want it to generate:

>>> np.ones(3)
array([1., 1., 1.])

>>> np.zeros(3)
array([0., 0, 0])

the simplest way to generate random numbers
>>> rng = np.random.default_(0)
>>> rng.random(3)
array([0.63696169, 0.26978671, 0.04097352])

You can also use ones(), zeros(), and random() to create a 2d array if you give them a tuple describing the dimensions of the matrix:

>>> np.ones((3, 2))
array([[1., 1.],
       [1., 1.],
       [1., 1.]])
>>> np.zeros((3, 2))
array([[0., 0.],
       [0., 0.],
       [0., 0.]])
>>> rng.random((3, 2))
array([[0.01652764, 0.81327024],
       [0.91275558, 0.60663578],
       [0.72949656, 0.54362499]])  # may vary


### Generating random numbers

The use of random number generation is an important part of the configuration and evaluation of manu numerial and machine learning algorithms. Whether you need to randonly initialize weights in an artificial neural network, split data into random sets, or random numbers (actually, repeatable pseudo-random numbers) is essential 

With Generator. integers, you can generate random integers from low(remember that this is incluse with) to high (exclusive). you can set endpoint = True to make the high number inclusive.

you can generate a  2x4 array of random integers between 0 and 4 with

>>> rng.integers(5, size=(2, 4))
array([[2, 1, 1, 0],
       [0, 0, 0, 4]])  # may vary
       

### How to get unique items and counts?

You can find a unique element in an array easily with 'np.unique'
for example, if you start with this array:

>>> a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

you can use np.unique to print the unique values in your array:

>>> unique_values = np.unique(a)
>>> print(unique_values)
[11 12 13 14 15 16 17 18 19 20]

to get the item of uniques values in a numpy array (an array of first index positions of unique valuesin the array), just pass the return_index argument in np.unique() as well as your array.

>>> uniques_values, indices_list = np.unique(a, return_index=true)
>>> print( indices_list)
[ 0  2  3  4  5  6  7 12 13 14]

you can pass the return counts argument in np.unique() along with your array to get frequencY count of unique values in a NumPy array.

>>> unique_values, occurrence_count = np.unique(a, return_counts=True)
>>> print(occurence_count)
[3 2 2 2 1 1 1 1 1 1]

This also works with 2d arrays! if you start with this array: 

>>> a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

you can find uniques values with:

>>> unique_values = np.unique(a_2d)
>>> print(unique_values)
[ 1  2  3  4  5  6  7  8  9 10 11 12]

if the axis argument isn't passed, your 2d array will be flattened.

if  you want to get the unique rows or columns, make sure to pass the axis argument. 
to find the unique rows, specify axis=0 and for columns, specify axis=1.

>>> unique_rows = np.unique(a_2d, axis=0)
>>> print(unique_rows)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


 To get the unique rows, index positionn, and accurrence count, you can use:

>>> unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
>>> print(unique_rows)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
>>> print(indices)
[0 1 2]
>>> print(occurrence_count)
[2 1 1]



### Transposing and reshaping a matrix

it's common to need to transpose your matrices. Numpy arrays have the property T to allows you to transpose a matrix.

You may also need to switch the dimmensions of a matrix. This can happen whem, for example, you have a model that expects a certain input shape that is different from your dataset. this is where the reshape method can be usefull. You simply need to pass in the new fimensions that you want for the matrix.

>>> data = np.arrange(1,7)
>>> data.reshape(2, 3)
array([[1, 2, 3],
       [4, 5, 6]])
>>> data.reshape(3, 2)
array([[1, 2],
       [3, 4],
       [5, 6]])

You can also use .transpose() to reverse or change the axis of an array according to the values you specify.
if you start witg this array:

>>> arr = np.arange(6).reshape((2, 3))
>>> arr
array([[0, 1, 2],
       [3, 4, 5]])

you can transpose your array with arr.transpose().

>>> arr.transpose()
array([[0, 3],
       [1, 4],
       [2, 5]])

You can also use arr.T;

>>> arr.T
       [1, 4],
array([[0, 3],
       [2, 5]])
       


### How to reverse an array

NumPy's np.flip() function allows you to flip, or reverse the contents of an array along an axis. When using np.flip(), specify the array you would like to reverse and the axis. If you don't specify the axis, NumPy will reverse the contents along all of the axes of your input array.

Reversing a 1d array

if you begin with a 1d array like this one:

>>> arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

you can reverse it with:

>>> reversed_arr = np.flip(arr)

if you want to print your reversed array, you can run:

>>> print('Reversed Array: ', reversed_arr)
Reversed Array: [8 7 6 5 4 3 2 1]

Reversing a 2d array

A 2d array works much the same way.
if you start with this array:

>>> array_2d = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

you can reverse the content in all of the rows and all of the columns with:

>>> reverser_arr = np.flip(arr_2d)
>>> print(reversed_arr)
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


You can easily reverse only the rows with:

>>> reversed_arr_rows = np.flip(arr_2d, axis=0)
>>> print(reversed_arr_rows)
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

Or reverse only the columns with:

>>> reversed_arr_columns = np.flip(arr_2d, axis=1)
>>> print(reversed_arr_columns)
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]

You can also reverse the contents of only one column of row. For example. you can reverse the contens of the row at index position 1 (the second row):

>>> arr_2d[1] = np.flip(arr_2d[1])
>>> print(arr_2d)
[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]

 You can also reverse the columns at index position 1 (the second column):

>>> arr_2d[:,1] = np.flip(arr_2d[:,1])
>>> print(arr_2d)
[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]



### How to access the docstring for more information

When it comes to the data science ecosystem, Python and NumPy aree biilt with the user in mind. One of the best examples of this is the built-in acces to documentation. Every object contains the refference to a string, which is known as the docstring. in most cases, this docstring contains a quick and concise summary of the object and how to use it. Python has a built-in help() function that can help you acces this information. This means that nearly any time you need more information, you can use help() to quickly find the information that you need.

for example:

>>> help(max)
Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.


Bevause acces to additional information is so useful, IPython uses the ? character as a shorthand for accessing this documentation along with other relevant information. IPython is a command shell for interactive computing in multiple languages.

for example:
in [0]: max?
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method


you can even use this notation for object methods and objects  themselves.

Let's say you create this array:

>>> a =  np.array([1, 2, 3, 4, 5, 6])

Then you can obtain a lot of usefull information ( first details about a itsel, followed by the docstring of ndarray of which a is an instance ):

In [1]: a?
Type:            ndarray
String form:     [1 2 3 4 5 6]
Length:          6
File:            ~/anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
        Shape of created array.
...



This also works for functions and other objects that you create. hust remember to include a docstring with you function using a string literal (''' ''' or """ """ aroung your documentation).

For ecample, if you create this function:

>>> def double(a):
  '''Return a * 2'''
  return a * 2

you can obtain information about the function;

In [2] double?
Signature: double(a)
Docstring: Return a * 2
File:      ~/Desktop/<ipython-input-23-b5adf20be596>
Type:      function


You can reach another level of information by reading the source code of the object you're interested in. Using a double question mark(??) allow you to access the source code .

for example:

In [3]: double??
Signature: double(a)
Source:
def double(a):
    '''Return a * 2'''
    return a * 2
File:      ~/Desktop/<ipython-input-23-b5adf20be596>
Type:      function

if the object in question is compiled in a language other than python, using ?? will return the same information as ?. you'll find this with a lot of built=in objects and types, for example:

In [4]: len?
Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

and:

In [5]: len??
Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

Have the same output because they were compiled in a proggramming language other then Python.



### Reshaping and flatterning arrays
view
There are two popular ways to flatten an array:
.flatten() and .ravel(). The rimary difference between the two is that the new array created using ravel() is actually a reference to the parent array (i.e.., a ''). This means that any changes to the new array will effect the parent array as well. Since ravel does not create a copy, it's memory efficient.

if you start with this array:

>>> x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

you can use flatten to flatten your array into a 1d array.

>>> x.flatten()
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

when you use a flatten, changes to your new array wont change the parrent array.

for example: 

>>> a1 = x.flatten()
>>> a1[0] = 99
print(x)  # Original array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
>>> print(a1)  # New array
[99  2  3  4  5  6  7  8  9 10 11 12]

but when you use ravel, the changes you make to the new array will effect the parent array.

For example:

>>> a2 = x.ravel()
>>> a2[0] = 98
>>> print(x)  # Original array
[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
>>> print(a2)  # New array
[98  2  3  4  5  6  7  8  9 10 11 12]

### Working with matematical fórmulas

the ease of implementing mathematical formulas that works on arrays in one of the things  that make Numpy so widely used in the scientific Python community.
For example the mean square error formula (a central formula used in supervised machine learning models that deal with regression);
implementing this formula is simple and straightforward in NumPy

    error = (1/n) * np.sum(np.square(predictions - label))

what makes this work so well is that predictions and labels contain one or a thousand values.  They only need to be the same size.

(look at the oficial numpy site, there are a lot of visual examples and explanetions that needs to be looked to a fully understand) 


### How to  save and load NumPy objects

You will, at some point, want to save your arrays to sdisk and load them back without having to re-run the code. Fortunately, there are several ways tis ave and load objects in numpy. Fortunately, there are several ways to save and load objects with NumPy . The ndarray objects can be saved to and loaded from the disk files with "loadtxt" and 'savetxt' functions that handle normal text files, 'load' and 'save' functions that handle Numpy binary files with a.npy file extension, and a 'savez' function that handles NumPy files with a.npz file extension. 

The .npy and ,npz files store data, shape, dtype, and other information required to reconstruct the ndarray in a way that allows the array to be correctly retrieved, even when the files is on another machine with different architetura.

If you want to store a single ndarray object, store it as a.npy file using "np.save". if you want to store more than one ndarray object in a single file, save it as a n.pz file using 'np.savez'. you can also save several arrays into a single file in compressed npz format with savez_compressed.

it's easy to save and load and array with np.save(). just make sure to specify  you want to save and a file name.
For example, if you create this array:

>>> a = np.array([1, 2, 3, 4, 5, 6])

you can save it as "filename.npy" with:

>>> np.save("filename",a)

you can use np.load() to reconstruct your array.

>>> b = np.load('filename.npy')

if you want to check your array, you can run::

>>> print(b)
[1 2 3 4 5 6]


You can csave a NumPy array as a plain text file like a .csv or .txt file with np.savetxt.

For example, if you create this array:
>>> csv_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])

You can sabe it as a .csv file with the name "new_file.csv" like this:

>>> np.savetxt('new_file.csv', csv_arr)

You can easily load your saved text file using loadtxt():

>>> np.loadtext('new_file.csv')
array([1., 2., 3., 4., 5., 6., 7., 8.])

the savetxt() and loadtxt() functions accept additional opitions parameters such as header, fooder, and delimiter. While text files canbe easily for sharing, .npy and .npz files are smaller andfaster to read. If you need more sophisticated handing of you text file( for example, if you need to work with lines that contain missing values), you will want to use the genfromtxt  function.

with savetxt, you can specify headers,footer, comments, and more.
s
